### ISSUE TITLE
error fetching channels: slack rate limit exceeded, retry after 3s

### ISSUE THREAD

**Issue by ritaniu0202** [rusq/slackdump#1]
Hi,

I keep getting the above message when I try to retrieve the channel list, even when I specify a channel id. Is there any way to fix it? 

Thanks!

**Comment by rusq** [comment]
Hey, @ritaniu0202 , even when you specify the channel id, the slackdump prefetches the list of channels to be able to resolve the references in the messages text.

I'll look into implementing handling of the rate limiting. Another option would be to disable prefetch on request forfeiting link resolving function.

**Comment by rusq** [comment]
@ritaniu0202, do you know approx how many channels does your workspace has?

What happens when you run: 
```
slackdump -c
```
?

**Comment by rusq** [comment]
This should be fixed now, please get the new build from the releases page.  Let me know if it persists.

**Comment by shi-bmz** [comment]
I'm seeing a similar problem when I try to download a single channel (it manages to get 820 files, then stops with the message "slack rate limit exceeded, retry after 1s").  Would it be possible to provide a command-line argument for adjusting the rate of requests?  I got this error on linux, then tried downloading the latest Windows build in the hopes that the extra delay imposed by my VPN connection might help (it didn't).
