### ISSUE TITLE
Feature request: Support naming output files/directories with the actual channel/DM name

### ISSUE THREAD

**Issue by tshddx** [rusq/slackdump#10]
This is easy enough to script in bash using the `-c` channel output, but it could be a nice feature to support this natively.

**Comment by rusq** [comment]
@tshddx sorry it took me a while to get to this, but it's resolved :)  you can use `-ft` to specify a name template.  For the channel name, this will do:

**Comment by tshddx** [comment]
> @tshddx sorry it took me a while to get to this, but it's resolved :) you can use `-ft` to specify a name template. For the channel name, this will do:
> 
> ```
> {{.Name}}{{if .ThreadTS}}({{.ThreadTS}}){{end}}
> ```
> 
> The output file will look like "general.json" for the channel and "general(123457890.123456).json" for a thread. (one of the examples in updated README)

Wow, nice work! Thanks!
