### ISSUE TITLE
Possible to export slack data with API token for migrating to mattermost?

### ISSUE THREAD

**Issue by luvwinnie** [rusq/slackdump#105]
**Is your feature request related to a problem? Please describe.**
Currently I'm trying to export the all slack messages including private and group message to mattermost. 

**Describe the solution you'd like**
I think having an option when API token(Admin) is avaiable to make a export full workspace would be great with this tool.

**Comment by rusq** [comment]
Hey @luvwinnie thank you, it seems Mattermost is gaining popularity - this is the second time someone mentions it.  I can implement a single token login, i.e. admin token, however my biggest problem would be testing it.  I'll have a look.

**Comment by luvwinnie** [comment]
@rusq currently I have tried export the data from official slack website and use [slack advanced exporter](https://github.com/grundleborg/slack-advanced-exporter) to link the email address and attachments to the exported zip file. It successfully imported to mattermost. It seems like if a full export data with private and group chats need to be a business member of the slacks. I was thinking maybe as long as I can export the chats with API tokens would be great.

I would like to take a look your code to see whether I can contributes ^^.

**Comment by ChenSun-Phys** [comment]
Doing some similar testing here in #107. @luvwinnie did you try to run slack advanced exporter with the Slackdump export by any chance? Any luck in getting the attachments filled there? Thanks.

**Comment by luvwinnie** [comment]
@ChenSun-Phys I haven't test with slackdump, I would like to try it later.

**Comment by rusq** [comment]
I have added the parameter `-export-token` which allows to specify an arbitrary token that will be added to each file in the export.

It is described in detail in the [Export](https://github.com/rusq/slackdump/blob/master/doc/usage-export.rst)

**Comment by rusq** [comment]
Hey, @luvwinnie - I'll close this issue for now, let me know if you have any issues, and I can reopen it.
