### ISSUE TITLE
What is the binary i need to use for MacOS (Intel) processor

### ISSUE THREAD

**Issue by jagatheesh** [rusq/slackdump#114]
Tried Installing with all 386 linux/openbsd/netbsd, but not working, giving exec format error. Appreciate any help.

**Comment by rusq** [comment]
It would help if you could tell what OS are you using?

**Comment by rusq** [comment]
Could you post output of
```
uname -a
```

**Comment by rusq** [comment]
Sorry, I must be blind!

For MacOS, please download "Darwin build": https://github.com/rusq/slackdump/releases/download/v2.2.0-alpha/slackdump-v2.2.0-alpha-darwin-arm64.tar.gz

It is also mentioned in documentation: https://github.com/rusq/slackdump/blob/master/doc/README.rst#id3

**Comment by rusq** [comment]
Updated Quickstart to explicitly mention macOS/Darwin

**Comment by jagatheesh** [comment]
Thanks, Rusq. Mine is a Intel MacOS.

I am getting below error

MacBook-Pro-9 ~ %. /Downloads/slackdump-v2.2.0-alpha-darwin-arm64\ \(1\)/slackdump ; exit;
zsh: **bad CPU type in executable:** /Downloads/slackdump-v2.2.0-alpha-darwin-arm64 (1)/slackdump

**Comment by rusq** [comment]
> Thanks, Rusq. Mine is a Intel MacOS.
> 
> 
> 
> I am getting below error
> 
> 
> 
> MacBook-Pro-9 ~ %. /Downloads/slackdump-v2.2.0-alpha-darwin-arm64\ \(1\)/slackdump ; exit;
> 
> zsh: **bad CPU type in executable:** /Downloads/slackdump-v2.2.0-alpha-darwin-arm64 (1)/slackdump
> 
> 

Sorry, my bad, this is the correct one for your arch:

https://github.com/rusq/slackdump/releases/download/v2.2.0-alpha/slackdump-v2.2.0-alpha-darwin-amd64.tar.gz

Initially I mistakenly posted arm arch.
