### ISSUE TITLE
For Slack users with blank display names, include  the attribute "display_name": ""

### ISSUE THREAD

**Issue by kjhosein** [rusq/slackdump#123]
**Describe the bug**
_[This is arguably not a bug, but if using the exports as a means to import the data into another tool that expects the Slack format, then it is.]_
If a Slack user's _Display Name_ isn't set, then `slackdump` does not include an attribute for it in the exports. 

**To Reproduce**
`slackdump -export <dir> <Channel-ID>` where 1 or more users in the conversation have blank display names.

**Expected behavior**
Include a `"display_name": "",` in the JSON. The native Slack exporter does this.

**Example JSON Output**
The `user_profile` block in the JSON should look like (this is a sample from the Slack exporter):

```
"user_profile": {
            "avatar_hash": "g38ae5c8db8x",
            "image_72": "https:\/\/secure.gravatar.com\/avatar\/f38ae5c8db89d6e4a997644ad609b7c0.jpg?s=72&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0008.png",
            "first_name": "KJH",
            "real_name": "KJH",
            "display_name": "",
            "team": "TGFDWL5H0",
            "name": "kjh",
            "is_restricted": false,
            "is_ultra_restricted": false
        },
```

I don't believe the last 2 attributes are strictly necessary, because I was able to perform a successful import (using a Slack to Discord tool) by simply adding in the  ` "display_name": "",` attribute.

**Comment by rusq** [comment]
I have merged the change into master, @kjhosein . Can build an executable for you, if you don't have go installed.  Let me know what OS are you using?

**Comment by kjhosein** [comment]
I'm on Linux (Debian) x86.

Thanks so much for the quick response!

**Comment by rusq** [comment]
No worries! Here you go:
[slackdump-linux.zip](https://github.com/rusq/slackdump/files/9464948/slackdump-linux.zip)

**Comment by kjhosein** [comment]
Thanks for this. Sorry to have (maybe?) wasted your time, but I had some time and figured out how to build the binary.

What's strange is that my build works and outputs `"display_name": "",`. The one you uploaded doesn't. 
Another point (which may not mean much) is my build is larger (13 MB) than yours (8.4 MB).

But at least we know the source code is good.

**Comment by rusq** [comment]
I know the answers!

1. I made a change on another computer, and on the one I built the binary I haven't run `git pull` 🤦‍♂️ 
2. Makefile target builds the binary with `-ldflags="-s -w"` which strips debugging symbols from the executable, reducing it's size.

Sorry!  I'm glad you figured that out :)

**Comment by kjhosein** [comment]
Haha, no worries. Happens to all of us, and all the time too! ;-)

Thanks for all of your help on this.
