### ISSUE TITLE
EZ-Login 3000: Automatically dismiss or suppress the cookie banner

### ISSUE THREAD

**Issue by mootari** [rusq/slackdump#126]
**Is your feature request related to a problem? Please describe.**

The EZ-Login 3000 is amazing and makes the login process dead simple. A very minor downside here is that it creates a fresh browsing context that will always show the cookie consent banner. Depending on the window size the banner may initially cover part of the login form.

**Describe the solution you'd like**

On Slack's own login form, dismiss the banner by programmatically by either:
- clicking the reject button programmatically via `document.getElementById('onetrust-reject-all-handler').click()`,
- or by setting the `OptanonAlertBoxClosed` cookie with a recent date value.

**Comment by rusq** [comment]
No wonder I haven't seen this banner - it does not appear if one is not in EU (I'm in Australia).  After I connected to a German VPN I saw it

**Comment by mootari** [comment]
> it does not appear if one is not in EU

Those banners are so universally present for me, I always forget it's only because of the GDPR.

**Comment by rusq** [comment]
I wish every site would be so courteous as to detect the country or region and check if this law applies.  This is merged, and it shouldn't be bothering anymore, EZ-login 3000 is even more EZ now :)
