### ISSUE TITLE
Cross-linking of Slackord and Slackdump

### ISSUE THREAD

**Issue by thomasloupe** [rusq/slackdump#138]
Hey there!

I'm the developer of Slackord: https://github.com/thomasloupe/Slackord
and 
Slackord2: https://github.com/thomasloupe/Slackord2

Many folks have mentioned to me that they really enjoy Slackdump!
I'd love if we were able to cross-link our readme's with a simple link to each other's repositories, as it seems like many come from your repository to mine, and lately I am sending folks over to yours as a means for them to export their slack history easily. Of course, I wanted to check if this was something you might be interested in. I plan on supporting Slackord2 for quite some time and it appears compatibility is already there between both.

Let me know if that might be something you're interested in.
Thanks!

**Comment by rusq** [comment]
Hey @thomasloupe,

Thanks for reaching out - of course, I'm all for it :)  I aimed to recreate the Slack export structure as it is, but as I was doing it from the scattered sources, there might be some inconsistencies, please let me know if there are any remaining compatibility issues that you're aware of that need to be sorted out.

**Comment by thomasloupe** [comment]
@rusq Thanks!
I'll look into this and get a testbed Slack set up with some additional data I can pull from Slackdump into Slackord2. I will open a new issue with any findings as to keep your issues nice and clean :)

I've added a link to Slackdump on the readme [here](https://github.com/thomasloupe/Slackord2/blob/master/README.md). Keep up the great work!

**Comment by rusq** [comment]
Hey @thomasloupe,

I updated a README and doc to include links to slackord2: https://github.com/rusq/slackdump/pull/140/files

Will merge shortly!

Thanks again for reaching out, looking forward for cooperation.

**Comment by thomasloupe** [comment]
As well am I! Thanks for the consideration!
