### ISSUE TITLE
slack rate limit exceeded (again)

### ISSUE THREAD

**Issue by shi-bmz** [rusq/slackdump#14]
I'm seeing a similar problem to #1 when I try to download a single channel (it manages to get 820 files, then stops with the message "slack rate limit exceeded, retry after 1s").  Would it be possible to provide a command-line argument for adjusting the rate of requests?  I got this error on linux, then tried downloading the latest Windows build in the hopes that the extra delay imposed by my VPN connection might help (it didn't).

_Originally posted by @shi-bmz in https://github.com/rusq/slackdump/issues/1#issuecomment-1019478033_

**Comment by rusq** [comment]
@shi-bmz the release doesn't have it yet, I wanted to implement #11  and #10  before tagging the next version. 

Can you try this build? I built the latest master, that has this fix.

[slackdump-linux.zip](https://github.com/rusq/slackdump/files/7921377/slackdump-linux.zip)
[slackdump-windows.zip](https://github.com/rusq/slackdump/files/7921378/slackdump-windows.zip)
[slackdump-darwin.zip](https://github.com/rusq/slackdump/files/7921376/slackdump-darwin.zip)

**Comment by foucist** [comment]
@rusq BTW, I tried the new build and it works!   Minor note - it's significantly slower on the initial fetch to 800 messages.  Might be using the wrong tier?  I assume the original speed would've been fine right up until the 429 retry happens.

**Comment by rusq** [comment]
I may have overdone it with throttling, I'll see if I can fine tune or ditch it altogether and rely just on slack rate limiting.

**Comment by rusq** [comment]
Hey @foucist, I've added a couple of params as described in #17 , here's the build if you want to give it a go.

[slackdump-windows.zip](https://github.com/rusq/slackdump/files/7933740/slackdump-windows.zip)
[slackdump-linux.zip](https://github.com/rusq/slackdump/files/7933739/slackdump-linux.zip)
[slackdump-darwin.zip](https://github.com/rusq/slackdump/files/7933738/slackdump-darwin.zip)

**Comment by foucist** [comment]
@rusq Nice, it's much faster now.  I didn't even notice if the 429 even got triggered so possibly could bump it up with limit-boost if needed, nice to have that option!   Quick question: do you need to cache the whole list of channels when I'm only dumping one specific channel?  It takes about 5 minutes to fetch the users & channels for the slack I'm testing with, I wonder if it would be worth saving a copy locally and assuming it hasn't changed within 2-4 hours.  That could save a big chunk of time if the command is run a bunch of times in a short period.

**Comment by rusq** [comment]
@foucist cool, I agree caching is questionable, I don't even remember what was the reason I did it for TBH, but removing it is on my TODO list.  Great to hear that it worked!

**Comment by rusq** [comment]
I'll close this one, created #18 to track the cache removal/optimisation

**Comment by shi-bmz** [comment]
@foucist thanks a bunch for this!  I tried the latest (linux) release that you posted above, and got:
`./slackdump: cannot execute binary file: Exec format error`
I then tried the (linux) version you posted previously, and it worked nicely -- thanks again!
