### ISSUE TITLE
Threads in text output, not just JSON output

### ISSUE THREAD

**Issue by craigrandall** [rusq/slackdump#15]
Hi @rusq.

I can confirm that the original JSON output does, in fact, contain expected thread content (e.g. the "slackdump_thread_replies" array). Unfortunately, the associated text output does not.

When is support planned for text output? Thank you

_Originally posted by @craigrandall in https://github.com/rusq/slackdump/issues/2#issuecomment-1020363214_

**Comment by craigrandall** [comment]
These reported results were from v1.1.1 (on Windows).

**Comment by rusq** [comment]
Cool, I haven't implemented yet, but probably should have already :) Will see into this after #11

**Comment by rusq** [comment]
Fixed in #20 :) @craigrandall
