### ISSUE TITLE
Remove the channel/users caching.

### ISSUE THREAD

**Issue by rusq** [rusq/slackdump#18]
User cache is mostly used for outputting the username in the text output
Channels? I don't remember.

**Comment by craigrandall** [comment]
Just a brief note that v1.2.1 performs SOOO much better than v1.1.1. Where I had rate limit issues before, they are gone! The text formatting of message threads is also most welcome. Thanks @rusq for the quick turnaround!

**Comment by rusq** [comment]
No problem :) Thanks for the feedback, I'm glad that it's useful.
