### ISSUE TITLE
[Feature request] export by date range

### ISSUE THREAD

**Issue by kubark42** [rusq/slackdump#182]
It'd be nice to be able to target a specific date range.

The use case is exporting slack messages on a daily basis and sending them to an archival mailman, such as groups.io.

**Comment by rusq** [comment]
Hey, thanks for the feedback.

Have you tried the following options?

**Comment by kubark42** [comment]
Hahah, 🤦!

I searched the repo for "time", "range", "slice", and "date", and didn't find any hits. Thanks for pointing out those options.
