### ISSUE TITLE
export data older than 3 months?

### ISSUE THREAD

**Issue by yusuke0324** [rusq/slackdump#190]
I followed the instruction below:
https://gilyazov.medium.com/downloading-your-private-slack-conversations-52e50428b3c2

but was able to export data within only 3 months.
I'm assuming this is because my workspace is a free plan but is there any way to export data older than 3 months?
I can still download older data via GUI that slack officially provides to export log.

I've tried -dump-from option but still got only recent 3 months data.

**Comment by rusq** [comment]
Hey @yusuke0324, unfortunately API does not return data older than 90 days, there's nothing that can be done from the client side, apart from paying $$$ to Slack to get the workspace on a paid plan.
The Slack UI export, almost certainly does not use the APIs to get all data.

The only thing I could suggest is to create the Slack export through the official UI, and restore it on a hosted [Mattermost Server](https://github.com/mattermost/mattermost-server), if you have an ability to host it somewhere and wish to maintain.  Better to spend $5 per month on VPS, than pay $7 per user/per month to Slack.  That seems what people were doing when Slack announced the 90-day restriction.

Sorry I can't help much with this.

**Comment by rusq** [comment]
Once you grab the "slack-export.zip" from the Slack UI, you can follow [this guide][1], to convert it to a Mattermost friendly format, and import all data and users.

[1]: https://docs.mattermost.com/onboard/migrating-to-mattermost.html#migrating-from-slack-using-the-mattermost-mmetl-tool-and-bulk-import

**Comment by rusq** [comment]
Hey, thanks for raising this, I feel that it would be beneficial for others to know, so I added it to the [FAQ](https://github.com/rusq/slackdump#faq)

**Comment by dshub-community** [comment]
Thank you for the suggestion! It was good to know that even the API has the 90 days limitation :(

**Comment by yusuke0324** [comment]
Thank you! It was good to know that even API has the limitation :(
