### ISSUE TITLE
Dump threads

### ISSUE THREAD

**Issue by tuftik** [rusq/slackdump#2]
Hello.

Is it possible also dump threads messages and files? Because it's a huge part of useful data :) For now at export results are only top level messages.

For info: 
- [Slack Help - Use threads to organise discussions](https://slack.com/intl/en-in/help/articles/115000769927-Use-threads-to-organise-discussions-);
- [Slack API - conversations.replies method](https://api.slack.com/methods/conversations.replies);

**Comment by rusq** [comment]
Hey, thanks for the suggestion, this tool initially pre-dates threads in slack - that would be a nice feature to have.  I'll have a look.

**Comment by rusq** [comment]
Hey @tuftik I have merged the change to master, let me know if it works for you?

Download is available in [this pre-release](https://github.com/rusq/slackdump/releases/tag/v1.1.0), let me know if it works on your workspace (works on mine, but everything usually works on developer's machine), and I'll mark it as release.

**Comment by craigrandall** [comment]
Hi @rusq.

I can confirm that the original JSON output does, in fact, contain expected thread content (e.g. the "slackdump_thread_replies" array). Unfortunately, the associated text output does not.

When is support planned for text output? Thank you
