### ISSUE TITLE
Error but process exit code is 0.

### ISSUE THREAD

**Issue by aijkl** [rusq/slackdump#203]
**Is your feature request related to a problem? Please describe.**
Exit code is returned 0 indicating normal even if it exits with an error

**Describe the solution you'd like**
If the program terminates with an error, please replace 1.

**Comment by rusq** [comment]
Hey @aijkl I checked all main code paths, and they all lead to termination with error code 1.

Could you please provide more details on this? What kind of error did you receive and got error code 0?

**Comment by aijkl** [comment]
Sorry, my mistake.
I'll close, thanks for a great app!
