### ISSUE TITLE
Date range parameters to only download data within a certain range

### ISSUE THREAD

**Issue by rhodessteve** [rusq/slackdump#210]
**Is your feature request related to a problem? Please describe.**
I need to download user data from a certain date range

**Describe the solution you'd like**
Command line options to set start and end date

**Describe alternatives you've considered**
Downloading everything and then deleting the JSON data files for the dates outside the scope

**Additional context**
This doesnt have to apply to DMs and can apply to channels only

**Comment by rusq** [comment]
It is [mentioned](https://github.com/rusq/slackdump/blob/master/doc/cli.rst?plain=1#L74-L82) in the CLI reference, but I guess it should be given more visibility, will do.
