### ISSUE TITLE
Is possible to dump Emojis with information about who created?

### ISSUE THREAD

**Issue by ericsouza** [rusq/slackdump#228]
Hi, my workspace é shared across others workspaces from the same org. Is it possible to download emoji with information about who created the emoji so I can match against the users export to get only emojis in my workspace?

**Comment by rusq** [comment]
Hey @ericsouza , when you running an emoji export, the index.json file contains the output of the API endpoint, and it does not have the user information. 

However, I quickly checked what kind of request the Slack Client sends, and it appears to be using the undocumented `api/emoji.adminList`, I'll see into this, no ETA, but can review the PR if submitted tho.

**Comment by rusq** [comment]
Implemented in Master, use `slackdump emoji -full` to get the usernames and IDs of the users.
