### ISSUE TITLE
slackdump -c does not work

### ISSUE THREAD

**Issue by jacknichols63** [rusq/slackdump#23]
Hello. 
slackdump -c does not work for me. My secrets.txt file has the two parameters SLACK_TOKEN and COOKIE provided but I am getting invalid_auth. 

Here is what I get:

❯ ./slackdump -c
2022/02/04 18:43:32 > caching users...
2022/02/04 18:43:32   caching users for the first time
2022/02/04 18:43:33 error fetching users: invalid_auth

**Comment by rusq** [comment]
Make sure that your SLACK_TOKEN and COOKIE are set to correct values (i.e. there's been no glitch when you copy/pasted them, ensure there's no space creeped in etc.)

It's easy to validate what values slackdump sees - run it with `-h` and the token and cookie value will appear as default values for `-t` and `-cookie` parameters respectively, i.e.
