### ISSUE TITLE
How to export direct messages? 

### ISSUE THREAD

**Issue by ImahnShekhzadeh** [rusq/slackdump#231]
Hi, 

First of all thanks for this app! 

I was wondering whether it's possible to export a specific DM with someone? I tried the `export` command and when I'm asked 

> ? Conversations to export (leave empty or type ALL for full export): 

I typed `ALL`, but when I ten look at the resulting `.zip` file, the resulting `dms.json` does not contain the direct messages... 

What I need is to export the DM's with a specific user, and I'm not quire sure how to specify this when asked the above question... 

Best, 
Imahn

**Comment by rusq** [comment]
Sorry, just noticed this question.

Yes, you can specify the ID of the conversation.

Refer to this doc: https://github.com/rusq/slackdump/blob/master/doc/usage-channels.rst#id7
