### ISSUE TITLE
Attachments downloaded in standard export although no -download flag

### ISSUE THREAD

**Issue by jo-chemla** [rusq/slackdump#232]
**Describe the bug**
When doing a standard export, then attachments are downloaded although there is no additional `-download` flag in the command. 

**To Reproduce**
Steps to reproduce the behavior: Run slackdump like this 
```bash
slackdump -export my-workspace -export-type standard
```

**Expected behavior**
Attachments should not be present. 

**Desktop (please complete the following information):**
 - OS: windows
 - slackdump version: latest v2.4.1

**Comment by rusq** [comment]
Hey @jo-chemla this is expected behaviour, and a design flaw: have a look at this #227 where I explained why this happens.

Also, thank you for a great suggestion of the download behaviour, I'll create a separate issue for it.

**Comment by jo-chemla** [comment]
Thanks for getting back! I also did not notice the no-download behavior - maybe the doc could clarify there are these 3 modes
 - nodownload (don't specify anything)
 - standard (add `-export-type standard`)
 - mattermost (add `-export-type mattermost `)

**Comment by rusq** [comment]
V3 will have updated logic, and this won't be necessary, I just need to find some time to finish it 😂
