### ISSUE TITLE
Incremental backup script is empty

### ISSUE THREAD

**Issue by iainelder** [rusq/slackdump#242]
PR #198 was supposed added an incremental backup script.

The [script file](https://github.com/rusq/slackdump/blob/cf51095e17e18c20f9684148f6514d257b621b59/contrib/incremental_backup/dump.sh) is empty.

Where can I find the backup script?

**Comment by rusq** [comment]
Nice catch, for some reason it got corrupt and I did not notice it.  [Fixed](https://github.com/rusq/slackdump/tree/master/contrib/incremental_backup)

**Comment by iainelder** [comment]
Thanks! I'll try it soon.
