### ISSUE TITLE
Add support for exporting own messages only from timeframe

### ISSUE THREAD

**Issue by razvanphp** [rusq/slackdump#264]
My usecase is rather interesting, but maybe also useful for other freelancers.

I want to be able to export all *my* messages from last month so I can calculate my hourly timesheet for invoicing.

I can easily select them in search, by choosing from:me and filter:range but pagination is awful and I can't programatically work on the dates and hours.

Thank you!
R

**Comment by razvanphp** [comment]
Seems like `/api/search.modules.messages` endpoint has this functionality, can we use it already with arbitrary parameters/query?

<img width="536" alt="Screenshot 2024-01-11 at 23 00 18" src="https://github.com/rusq/slackdump/assets/4599319/a09062c5-f27e-4459-bff4-269c8983bf87">

**Comment by rusq** [comment]
Hey @razvanphp, thank you for the suggestion.  I think once I get the v3 out, this would be a great feature to have, I'll add it in v3.1 milestone.

**Comment by rusq** [comment]
Will be added in v3.0

**Comment by razvanphp** [comment]
Yes! it worked, thank you!

Now I have to write my own script for parsing and calculations 🙂

**Comment by razvanphp** [comment]
Hey @rusq, tried again the feature and observed a small bug: the output file is not a valid json, it misses the array `[]` wrapper and `,` in between the objects. Is this expected?

<img width="667" alt="Screenshot 2024-06-05 at 18 03 21" src="https://github.com/rusq/slackdump/assets/4599319/c7a0dcdf-724e-401d-894b-34962b6f8c36">



Otherwise it works great, I published my script as a [gist](https://gist.github.com/razvanphp/0f0f83eb3318b054b0dc7b81b5fa16c6).

![slack heatmap 03 2024](https://github.com/rusq/slackdump/assets/4599319/ad2185c3-2566-4505-a2fe-77599545b3ac)

**Comment by rusq** [comment]
Hey @razvanphp , the output file is a valid JSONL document, where each line is a JSON object.  This is done to reduce memory usage.  If I was to assemble an array of million messages, that would take considerable amount of RAM, so JSONL shifts that problem to the user

**Comment by kisst** [comment]
Pagination seems to be missing from this `search` function, I only get the first 70 matches, while there in the app the same search returns 65k messages.

**Comment by rusq** [comment]
@kisst , thanks, I don't remember there was an issue last time I checked, interesting.  I'll have a look.

**Comment by rusq** [comment]
I cannot confirm this.

To check the number of unique message you can run the following command on the `search.jsonl.gz`:
```
gzcat ./search.json.gz |grep '"t":10' | jq '.sm' | jq '.[].ts' | sort | uniq | wc -l 
```

It selects all JSON chunks of type 10, then extracts the message slice "sm", from each message it extracts the "ts" of the message, which is usually the time when the message was posted, the sorts them alphabetically, filters unique values and counts the lines.

In my example, in the Client I could see 487 messages, and the above command returns 487.

**Comment by rusq** [comment]
Retested on 16K message search results, still no problem.  @kisst, I'm closing this, but would be great if you could retest with latest master and share the exact command you're running?

**Comment by kisst** [comment]
I don't have access to the same workspace any-more which has such an extensively long history so can't re-test with the same conditions.

**Comment by rusq** [comment]
@kisst no worries, I'm pretty sure it should be working as expected.  Thanks for your report
