### ISSUE TITLE
Error when dumping channel with files, when there are files that was deleted.

### ISSUE THREAD

**Issue by svantek-admin** [rusq/slackdump#270]
**Describe the bug**
When doing dump of Slack channel which downloading files I get following error 

`error saving "XXXXXXXXXX-" to "aaaaa/attachments": callback error: download to "aaaaa/attachments/XXXXXXXXXX-" failed, [src=]: received empty download URL`

it seems that when there were file in message but later was deleted, slack returns array with file which "mode": "tombstone"

When this happens, malformed URL is added in exported file

```
        "url_private": "attachments/XXXXXXXXXX-",
        "url_private_download": "attachments/XXXXXXXXXX-",
```

**To Reproduce**
1. Create channel in slack
2. Upload file
3. Delete this file
4. Run slackdump -download on this channel

**Expected behavior**

No attempt to download file is performed

**Desktop (please complete the following information):**
 - OS: Linux
 - OS Version: Ubuntu 22.04
 - Slackdump Version: 2.5.4

**Comment by rusq** [comment]
Hey @svantek-admin, thanks for the report,  I thought tombstones are handled in the code, but I'll double check.

**Comment by rusq** [comment]
@svantek-admin, this is fixed now, sorry for the inconvenience.  I did handle tombstones, but in the dev (v3) branch ¯\\\_(ツ)\_/¯
