### ISSUE TITLE
Exits at login stage

### ISSUE THREAD

**Issue by doppelganger007** [rusq/slackdump#289]
**Describe the bug**
I choose Email (automatic) and then input my Slack login info on the login screen. When I hit return, the window closes but nothing else opens. The same thing happens when I try other login options (Email manual, Manual, SSO).

**Authentication type (please read)**
Tried entering my information manually and using SSO sign-on with Google.

**To Reproduce**
1. Run slackdump from Windows Command Prompt. Follow the tree of choices to anywhere that eventually leads to a login page.

**Expected behavior**
I'm guessing a window's supposed to pop up showing that I've logged in, so that I can proceed with the export.

**Output**
The Slackdump window disappears and no information appears.

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 23H2 (Windows 11 Home)
 - Slackdump Version: 2.5.8

**Comment by KrisPistofferson** [comment]
Hi @doppelganger007 
Did you have any luck with this?
I'm getting the same issue

Thanks

**Comment by rusq** [comment]
Hey, friends, sorry about the delay.  What version are you both using?

For version 2.5+
1. Run the auth reset to ensure that nothing is left: `.\slackdump.exe -auth-reset`
2. Try `-legacy-browser` command line switch like so:

```
.\slackdump.exe -legacy-browser <add your switches and ids>
```

For version 3.0+:
1. Run uninstall: `.\slackdump.exe tools uninstall`
2. Run with legacy browser `.\slackdump.exe workspace new -legacy-browser <your workspace>`

**Comment by KrisPistofferson** [comment]
Hi @rusq 

Thanks for getting back.
I was running 2.5.8 right out of file explorer (selecting options with the arrows)
Do you reckon I'll have more luck if I try the long version through terminal?

Many thanks

**Comment by rusq** [comment]
Hey @KrisPistofferson, you might have tried already, and it might have not worked.  I think your best bet for now is do the manual token extraction, until I get around to fix this.

**Comment by rusq** [comment]
@doppelganger007 , just noticed that you have specified the version as "Windows Store 4.38.115 64-bit".  What is this magic?

**Comment by doppelganger007** [comment]
@rusq I have no idea what that means . . . The Slackdump version I'm using is 2.5.8. 

Sorry for the delay in responding, and for this ignoramus question: In your instructions for 2.5+ versions, what do you mean by <add your switches and ids> with the -legacy-browser command? I ran the auth reset already.

**Comment by rusq** [comment]
Slackdump has two different libraries built in to manipulate the browsers:
- rod, that is using CDP (Chrome DevTools Protocol)
- go-playwright, that is using playwright, a browser-agnostic automation that is done through the javascript layer, also, it's a great pain in the arse to upgrade, always something breaks.

They both do the same thing, but differently.  In the long run, there's a plan to kill playwright due to maintenance burden each time the upgrade is needed.

When one specifies `-legacy-browser` flag, it uses playwright.  Otherwise, it uses rod.

**Comment by rusq** [comment]
Tested yesterday on Win 10 (I don't have hardware for Win 11), everything worked, I suspect the browser automation libraries update would have fixed that by I have no way to test

**Comment by KrisPistofferson** [comment]
Hi @rusq 

I followed instructions you listed on another page for creating a secrets.text file and ran everything through command prompt and it has all worked beautifully
slack dumped!

I did it a few weeks ago, sorry for the late update

How do I buy you a coffee/pint?

**Comment by rusq** [comment]
Great to hear, thank you!

Thank you for offering coffee it is not necessary, but if you insist, [here's the link](https://ko-fi.com/rusq_) 😂
