### ISSUE TITLE
[v3-wiz] Dump only gives UserIDs and not actual real names

### ISSUE THREAD

**Issue by chriscowan** [rusq/slackdump#294]
**Describe the bug**
doing a dump of a channel will only dump the UserID's and not translate them to real names.

**To Reproduce**
1. slackdump dump @channels.txt

**Expected behavior**
I would expect it to give me the real names of the users instead of just the userIDs and not rely on doing a HUGE "slackdump list users", which is not possible due to the sheer amount it would grab. i tried using "slackdump format -online csv <json>" but i get 

```
format: 2024/06/26 14:30:37 Detected dump type: "Conversation"
format: 2024/06/26 14:30:37 Error 006 (Application Error): internal error:  no provider in context
Error 006 (Application Error): internal error:  no provider in context
```

still not sure if that would solve my use case either though.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS Version: Ventura 13.6.7
 - Slackdump Version: v3-wiz

**Additional context**

**Comment by rusq** [comment]
This is not what dump is conceived to do.  Dump produces slightly augumented, but still raw API output.  It does not resolve user IDs.  But it seems like a nice suggestion, however, i'm not sure when I'll be able to implemented.

And as always, PRs are welcome, if you want to implement this.

**Comment by chriscowan** [comment]
Thanks for the reply. I ended up calling the slack api user.info, then just maintaining a csv with the user ID and real name to reference to prevent any future throttling. Works with enterprise so seems to satisfy my use case for now. 👍
