### ISSUE TITLE
404 Image couldn't be view on Slack export viewer/logs viewer 

### ISSUE THREAD

**Issue by Winniepoom** [rusq/slackdump#307]
**Describe the bug**
I am using Slack Dump 2.5.8 to export a standard export file and download it. However, when I try to view my data on Slack Export Viewer and Slack Log Viewer, it does not show any images. When I click on the broken image, it gives me a 404 error.

**Authentication type (please read)**
Manual login 

**To Reproduce**
1. export with standard export file with standard login
2. run slack export viewer with command  `slack-export-viewer -z `

**Expected behavior**
To be able to preview or click to view images in Slack Export Viewer
**Output**
here my logs.
```
 * Running on http://localhost:5000
Press CTRL+C to quit
127.0.0.1 - - [25/Jul/2024 16:48:23] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [25/Jul/2024 16:48:23] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [25/Jul/2024 16:48:23] "GET /static/viewer.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [25/Jul/2024 16:48:23] "GET /static/viewer.css HTTP/1.1" 304 -
127.0.0.1 - - [25/Jul/2024 16:48:28] "GET /attachments/F*71****3S-******** HTTP/1.1" 404 -
```

**Desktop (please complete the following information):**
 - OS: windows 10
 - OS Version: [e.g. 14.1]
 - Slackdump Version: 2.5.8
 
**Additional context**

**Comment by rusq** [comment]
In SlackLogViewer and slack-export-viewer images can not be previewed, unless a valid token is added during export with `-export-token` flag (see [CLI reference](https://github.com/rusq/slackdump/blob/master/doc/cli.rst).

But! Slackdump v3 has a built-in viewer, but it's in pre-alpha stage, most features are implemented, but things still might break.

To use it you will need to have Go installed on your system.

Once you have go installed
```
go install github.com/rusq/slackdump/v3/cmd/slackdump@latest
```

and then run

```
slackdump view <your-export-file-or-directory>
```

**Comment by Winniepoom** [comment]
@rusq 
When I try to run a view command  it throw me an error here said that my path is invalid. I'm pretty sure that my path is correct maybe the syntax ? any idea how to solve this ?
```
C:\Users\Admin\Downloads\slackdump_Windows_x86_64> .\slackdump.exe view C:\Users\Admin\Downloads\slackdump_Windows_x86_64\output\export.zip
Slackdump 2.5.9 (commit: 4c6cfcf300e22c9ea36e4692799af188900bc21f) built on: 2024-07-25T12:08:01Z
2024/07/26 10:30:50 invalid link: "C:\\Users\\Admin\\Downloads\\slackdump_Windows_x86_64\\output\\export.zip"
```

**Comment by rusq** [comment]
If you refer to my original comment, you'll notice that only v3 supports viewing exports.  You're running v2.5.9
