### ISSUE TITLE
Exporting Data Beyond 90 Days with Paid Subscription in Slack Dump Export ?

### ISSUE THREAD

**Issue by Winniepoom** [rusq/slackdump#310]
Hello,

I have a quick question about Slack Dump Export. If I switch to a paid subscription, will I be able to use Slack Dump Export to access and export data beyond the past 90 days? I want to confirm this before deciding on a paid plan.

Thank you!

**Comment by rusq** [comment]
Slackdump will be able to retrieve messages beyond 90 days for users on the paid Slack subscription, if there are any.

**Comment by Winniepoom** [comment]
@rusq That great. Thank you for your answering.
