### ISSUE TITLE
Missing files or incorrect readme; cannot run

### ISSUE THREAD

**Issue by KingSupernova31** [rusq/slackdump#315]
The readme says:

> Run the ./slackdump or slackdump.exe executable

But there is no file named `slackdump` or `slackdump.exe`.

**Comment by rusq** [comment]
Hey @KingSupernova31 , have you checked [Releases page](https://github.com/rusq/slackdump/releases/tag/v2.5.10) ?

**Comment by KingSupernova31** [comment]
Ah, ok, I see what happened. I thought I was supposed to download the release source code, but no, I'm supposed to look at the list of files under "assets" and pick the one for my OS. That's rather unclear from the readme, and particularly so given that there's no "darwin" file under "assets" like the readme claims there is. Also it seems that the main repository readme is different from the readme for the latest release.

**Comment by rusq** [comment]
If you look in the [Readme’s Quick Start](https://github.com/rusq/slackdump?tab=readme-ov-file#quick-start) you’ll find the link to the releases.

Of course, if you want, as per your original intent, you can download the source code and build it yourself, there are build instructions.

Or, if you want v3, you can install it with:
```
go install github.com/rusq/slackdump/v3/cmd/slackdump@latest
```

As for the difference of the readme:
- Master branch is version 3 right now, for inquisitive ones, it has support for the enterprise instances, for example, and a viewer of exported data.
- Readme in the archive is from the “v2” branch, which stands for “version 2”.

If you know a better way that could make it more clear, please submit a Pull Request with changes ¯\\_(ツ)\_/¯

**Comment by rusq** [comment]
Updated the v2 readme to remove Darwin reference as well.
