### ISSUE TITLE
Failure after entering 2FA-Code

### ISSUE THREAD

**Issue by indika-dev** [rusq/slackdump#322]
**Describe the bug**
Our Slackworkspace is secured by 2FA. I started slackdump with automatic login and after entering username/password and 2FA-code, I'll get the following error message:
<details>
<summary>error log from slackdump</summary>
Slackdump 2.5.11 (commit: eff22d042cda7766d8af134da8296efe23059a05) built on: 2024-08-27T08:25:06Z
Logging in to Slack, depending on your connection speed, it will take 15-30 seconds...
authenticated.
2024/09/10 09:23:50 failed to authenticate:  please double check that token/cookie values are correct (error: authentication error: invalid_auth)
</details>

**Authentication type (please read)**
I tried to authenticate via:
-  Email (manual)
- Email (automatic, experimental)
- Other/Manual 

**To Reproduce**
1. Run slackdump with or without commandline arguments
2. Answer questions, what to export or dump
3. Browser will open or commandline will ask for your emailadress in Slack
4. Enter password/email confirmation code
5. Enter confirmation code
6. abort with error message from above 

**Expected behavior**
slackdump will recognise, that it is successfully authenticated(as written by slackdump in log) and will download the configured content.

**Output**
see log in problem description

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - OS Version: 22.04.4 LTS
 - Slackdump Version: 2.5.11 (commit: eff22d042cda7766d8af134da8296efe23059a05) built on: 2024-08-27T08:25:06Z

**Additional context**

**Comment by rusq** [comment]
Thank you for the report.  Could you please try running with "-legacy-browser" flag and see if that works?

**Comment by rusq** [comment]
Are you on the enterprise slack workspace?  If you are, you'll need to compile v3, and run it with `-enterprise` flag.  v2 does not support enterprise instances.

**Comment by indika-dev** [comment]
>  Are you on the enterprise slack workspace? If you are, you'll need to compile v3, and run it with -enterprise flag. v2 does not support enterprise instances.

I'm on a Business+-Plan with 2FA. I will try this and report back.

**Comment by rusq** [comment]
Hey @indika-dev, did it wok?

**Comment by stevetranby** [comment]
Same, once you enter 2FA you get a "Launch Slack App", same with `-legacy-browser`

**Comment by rusq** [comment]
Fixed in #326
