### ISSUE TITLE
Terminal app support for default browser

### ISSUE THREAD

**Issue by NGWi** [rusq/slackdump#325]
**Is your feature request related to a problem? Please describe.**
I am using  slackdump_macOS_arm64 2.5.11.
I tried using the terminal app (open slackdump), but the auth workflow always opens up Chromium, where Google auth is not currently supported.

**Describe the solution you'd like**
Please make the default behavior that it opens up the user's default browser.

**Describe alternatives you've considered**
Running the terminal commands "./slackdump -export my-workspace.zip -export-type standard" did work. Once I successfully did it once that way the terminal app did not require auth, so it also worked.

Thanks a ton for the tool!

**Comment by rusq** [comment]
Hey @NGWi, when you say "Google Auth is not supported", what do you mean?  You can't login into Google Workspace?  I think there's a possibility to connect to Google Chrome currently installed on the system, but I need to check to be sure.

**Comment by rusq** [comment]
EZ-Login now prioritises OS browser over Chromium in the following order:
- Brave
- Chrome
- Edge
- Chromium
- Installs it's own.

**Comment by rusq** [comment]
#327

**Comment by NGWi** [comment]
Thanks a ton, Rustam!
