### ISSUE TITLE
EZ-Login doesn't work with Google Auth

### ISSUE THREAD

**Issue by rusq** [rusq/slackdump#334]
Hey,
sorry, I forgot the important details.
- chromium what the slackdump downloaded automatically
- google auth, but when I select the email auth or manual, and then the google option from the browser, I got the same error
- if I use the manual, and then I supply the username/pw and I select the "use Slack in your browser", then it works.
![Screenshot from 2024-10-06 19-59-57](https://github.com/user-attachments/assets/f5c3bddf-cd6d-4a95-895d-36ed2de7d0f7)

_Originally posted by @balazs300 in https://github.com/rusq/slackdump/issues/328#issuecomment-2395530340_

**Comment by rusq** [comment]
Upstream issue: https://github.com/go-rod/rod/issues/1033

**Comment by rusq** [comment]
Slackauth PR: https://github.com/rusq/slackauth/pull/18

**Comment by rusq** [comment]
V3: #335 
V2: #336 

Merged.

**Comment by tddschn** [comment]
I'm using `Slackdump 2.5.15 (commit: 1ce4bf0181e5e546068ab8d59f144aa570af72a6) built on: 2024-10-08T12:09:46Z` on macOS and the issue persists. @rusq

**Comment by rusq** [comment]
@tddschn can you provide more details? What is the command line? What are your choices in the menu? What is the error you are seeing?

**Comment by rusq** [comment]
I just tested it from scratch, and it authed ok.  I'll create a wiki article, so that anyone could follow.

**Comment by rusq** [comment]
@tddschn Please follow this guide, and let me know if you have any issues:
https://github.com/rusq/slackdump/wiki/EZ%E2%80%90Login-3000#google
