### ISSUE TITLE
failed to initialise the auth provider: browser automation error: failed to create blank page: EOF

### ISSUE THREAD

**Issue by thomasklein** [rusq/slackdump#343]
**Describe the bug**

Trying to login I end up with "failed to initialise the auth provider: browser automation error: failed to create blank page: EOF".

I tried 

```
./slackdump -browser firefox msg-id
./slackdump -browser chromium msg-id
```

running it in the terminal, I noticed that the terminal looses focus for a moment and then above error message is displayed.

**Authentication type (please read)**

Okta

**Output**
**Desktop (please complete the following information):**
 - OS:  macOS]
 - OS Version: 15.0.1 (24A348)
 - Slackdump Version: 2.5.15

**Comment by rusq** [comment]
Hey @thomasklein,

You can try running with `-legacy-browser` and see if that helps - will use different automation library.  This page might help understanding the auth process: https://github.com/rusq/slackdump/wiki/EZ-Login-3000

Also,  when presented with auth choices, what kind of auth are you selecting?

**Comment by rusq** [comment]
Alternatively, you can try selecting "Google Auth" - it will (try) using your browser with the current user profile.
