### ISSUE TITLE
Channel not found – how to select / reset / change workspace?

### ISSUE THREAD

**Issue by LinusGeffarth** [rusq/slackdump#348]
I've previously authenticated and exported a workspace successfully. Now, I want to export a channel _from a different workspace_. When going through the steps, slackdump does _not_ ask for the workspace url/name or provide another way to select/reset the workspace.  
I'm assuming, it's smart enough to remember the authentication and the workspace, but maybe multiple workspaces is an edge case not considered 😄

How can I work around this? I guess I could de-install slackdump and then install it again, but that's rather tedious.

Or maybe it's just me and I'm doing it wrong. If so, please point me in the right direction.
Thank you!

**Comment by rusq** [comment]
Hey @LinusGeffarth , you have 2 options
#### version 2
With version 2 - you can do `-auth-reset`, then slackdump will remove the saved credentials, and you will be offered to log in again
### version 3
Version 3 supports and stores credentials for multiple workspaces, run 
```
go run ./cmd/slackdump help workspace
```
to see your options.  `new` authenticates in the new workspace, `select` switches between workspaces, `list` shows all stored workspaces.
