### ISSUE TITLE
Please remove flags which hinder reproducibility

### ISSUE THREAD

**Issue by deknos** [rusq/slackdump#369]
**Describe the bug**
You are adding flags to the binary like commit, version and especially date, which do not belong in a binary. Please think if you omit them, because it hurts reproducibility, see also https://reproducible-builds.org/docs/commandments/

If you really want commit and version in your code, please omit at least the date, as many opensource buildsystems will want to set this to the EPOCH DATE which is the beginning of unixtime

**Expected behavior**

remove at least "-X 'main.date=$(BUILD_DATE)'" from build

**Comment by rusq** [comment]
Hey @deknos, is there a specific problem you're trying to solve, i.e. you're dealing with an opensource buildsystem that has a problems with having a date in the build, or is it a theoretical possibility?

**Comment by rusq** [comment]
Added the ability to specify the BUILD_DATE in d2611ddd11a872bf0d9e5a688dd678b2e0150246

```
BUILD_DATE="love_and_reproduce" make clean slackdump
```

```
$ ./slackdump version
Slackdump v3.0.0-alpha-3-gd2611dd (commit: d2611dd) built on: love_and_reproduce
```

**Comment by deknos** [comment]
Hi @rusq ,
yes, i packaged it for opensuse, and the date in the buildfile is something which goes against the best practices we have to employ there. I mean, version and commit are still okay, but at least date has to be able to be set to something else. Also at least at the moment i do not use your Makefile, but i am still considering if i would do this.

also, i packaged 2.6.0, i am still getting used to your tool :)

**Comment by rusq** [comment]
Oh, nice! Thanks for that @deknos.

Let me know if you need a hand with building it and if this solution works for you?

**Comment by deknos** [comment]
I built it successfully (https://build.opensuse.org/package/show/home:dknorr/slackdump) but i will probably make a small PR later that day, and there's also the issue of using an already installed browser (the other ticket). I also requested access to your telegram channel :)
