### ISSUE TITLE
Cannot use system browser firefox on linux

### ISSUE THREAD

**Issue by deknos** [rusq/slackdump#370]
**Describe the bug**
I want to use my system browser for authentication. I am already logged in into my enterprise slack workspace with an commercial OAuth Provider. I don't know though if they use OAuth/OpenID for authenticating against slack. 

**Authentication type (please read)**
Interactive starts downloading chrome from the internet, even with -browser=firefox and selecting "User Browser" just stops and says it does not find a browser:

**To Reproduce**
```
benutzer01@localhost:~/tmp/slackdumptest> slackdump  -browser=firefox -w mycompany -base=/home/benutzer01/tmp/slackdumptest/t1 https://mycompany.slack.com/archives/D05K22ALVTR
Slackdump dev (commit: placeholder) built on: 2077
```

With tag 2.6.0 and with github master branch

**Expected behavior**
I can authenticate in the open browser, firefox, installed on the system (linux, opensuse tumbleweed) where i am logged into my  slack workspace

**Output**
```
benutzer01@localhost:~/tmp/slackdumptest> slackdump  -browser=firefox -w mycompany -base=/home/benutzer01/tmp/slackdumptest/t1 https://mycompany.slack.com/archives/D05K22ALVTR
Slackdump dev (commit: placeholder) built on: 2077
```

**Desktop (please complete the following information):**
 - OS: OpenSUSE Tumbleweed (rolling release)
 - Slackdump Version: 2.6.0 and current master branch

**Comment by deknos** [comment]
do i have to close my browser perhaps?

**Comment by rusq** [comment]
Hey, you'd have to use the `-legacy-browser` flag:
https://github.com/rusq/slackdump/wiki/EZ-Login-3000#using-playwright-instead-of-rod

**Comment by rusq** [comment]
Yes, as long as it's not a firefox.

In the auth menu, one must choose "User Browser"
![image](https://github.com/user-attachments/assets/1b2de89e-6748-4542-aed8-1e71015689fe)

Then it offers the list of compatible (Chromium-based) browsers installed on the system
![image](https://github.com/user-attachments/assets/04ef48f3-2c24-480c-b08b-124597217f59)

**Comment by rusq** [comment]
I'll reopen this for convenience

**Comment by deknos** [comment]
Okay, it works. funnily it lists 4 instances of chromium, though i installed only chromium and flatpak chromium. and even after removing the flatpak it still listed four chromium instances.

Any chances you will reenable firefox as well?

**Comment by rusq** [comment]
I have nothing against firefox, the [library](https://github.com/go-rod/rod) I use for browser automation uses Chrome Devtools Protocol, and firefox is not supported.

The [previous library](https://github.com/playwright-community/playwright-go) (engaged with -legacy-browser) supports firefox, but it pulls a ton of dependencies, including nodejs and playwright js layer + browser, and also it needs a "[specific version of the browser](https://playwright.dev/docs/browsers)", so it wouldn't be able to interact with the user browser.  Also, there were so many times that the upstream changes broke the API, so I decided to gradually get rid of it.

**Comment by rusq** [comment]
I'll see into adding a path to the browser selection screen, so it would be obvious which is which

**Comment by deknos** [comment]
Okay, as well as it works with a system-installed chromium-based browser, i am fine :) I do not want to create more work for you.

**Comment by rusq** [comment]
Just checked - it should already display the browser path in the description for the highlighted browser.
