### ISSUE TITLE
Importing a slackdump export back into slack does not import attachments correctly

### ISSUE THREAD

**Issue by codeallthethingz** [rusq/slackdump#371]
**Describe the bug**
I used slackdump 2 (Slackdump 2.6.0 (commit: Homebrew) built on: 2024-11-03T04:34:16Z) to export from slack in to the slack export format as a zip file.  When I re-import it to a new slack workspace, the files show up, but they are all shown as a squid proxy html file.

Example:

<img width="621" alt="image" src="https://github.com/user-attachments/assets/1845b3b4-162a-4f25-bb16-a637646c8846">

When I inspect the file I get

```
➜ head -10  ~/Downloads/cats.gif
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>ERROR: The requested URL could not be retrieved</title>
<style type="text/css"><!--
 /*
 * Copyright (C) 1996-2023 The Squid Software Foundation and contributors
 *
 * Squid software is distributed under GPLv2+ license and includes
 * contributions from numerous individuals and organizations.
```

**Authentication type (please read)**
Browser login

**To Reproduce**
1. Ran `slackdump -export my_export.zip -download https://XXXXXXXX.slack.com/archives/C083GMYN0G7`

**Expected behavior**
A zip file that can be successfully imported to slack with attachments present.

**Output**
n/a

**Desktop (please complete the following information):**
 - OS: macOS
 - OS Version: 14.6.1 (23G93)
 - Slackdump Version: Slackdump 2.6.0 (commit: Homebrew) built on: 2024-11-03T04:34:16Z

**Additional context**
I feel like this is something to do with the export API key mentioned but I'm not sure where to get it or how to create one.

**Comment by rusq** [comment]
Hey @codeallthethingz , that wouldn't work with slackdump.

There are two things at play:
1. Canonical Slack exports never have the attachments in them, therefore;
2. Slack import does not expect to see any attachments in the zip file.  What it expects to see is a valid URL of the file, where it can reach out and fetch, and based on the description provided, it did exactly that.

One of the possible solutions would be to:
1. make a simple service that serves the attachments from the local machine through some proxy, i.e. Ngrok
2. update all links in slack export to point to a URL of Ngrok+path to the file.

With the flexibility of Ngrok, in theory, Slackdump could serve as an attachment server, but at the moment, there's no such ability.

**Comment by codeallthethingz** [comment]
@rusq this is what I created to get the zip file into a state that I could reverse proxy server from - https://gist.github.com/codeallthethingz/38e340d15b26dc0b75e455aae37df8e2
