### ISSUE TITLE
Dump custom emojis

### ISSUE THREAD

**Issue by craigrandall** [rusq/slackdump#44]
Since custom emojis are an important aspect of Slack instance culture/comms, perhaps it makes sense for SlackDump to also dump custom emojis (e.g. via a new flag/arg/param to slackdump).

https://github.com/jason0x43/alfred-slack/blob/master/emoji.go provides one examples of leveraging the appropriate Slack API: https://api.slack.com/methods/emoji.list.

Thank you for considering!

**Comment by rusq** [comment]
@craigrandall sorry, it's taking me obscene long time to get to this.

Let me ask - do you see it as a separate mode, i.e. `slackdump -emoji` and it would dump the json definiton of those emojis along with png/gif files for them?

**Comment by craigrandall** [comment]
No worries! This is open source after all. I appreciate all of your hard work--as you can get to it. Thank you!

Yes, I did see it more as a separate mode since it is somewhat orthogonal to channel content--similar to a user list. In terms of output, yes, that is roughly what I envisioned, where GIF would include animated support, if applicable.

Thanks for asking

**Comment by mootari** [comment]
Just in case it's helpful in any way (e.g. for testing purposes), here's a JavaScript snippet that I've been using to fetch the list of custom emojis on the client side, via dev tools:
```js
await (async (teamId) => {
  const {token} = JSON.parse(localStorage.localConfig_v2).teams[teamId];
  const query = (marker) =>
    fetch(`https://edgeapi.slack.com/cache/${teamId}/emojis/list`, {
      body: JSON.stringify({ count: 100, token, marker }),
      method: "POST",
      credentials: "include"
    }).then((r) => r.json());
  const results = [];
  let marker;
  do {
    const data = await query(marker);
    results.push(...data.results.map((d) => [d.name, d.value]));
    marker = data.next_marker;
  } while (marker);
  return Object.fromEntries(results);
})('THE_TEAM_ID')
```
This collects the image URLs, but doesn't resolve aliases.

**Comment by rusq** [comment]
Edge api are dodgy to deal with as there's no documentation, I'll put this snippet to a good use, thank you!

**Comment by rusq** [comment]
@craigrandall finally! Merged the emoji dump to master, it will be available in the v2.2.0, which I release soon.  Thank you for the wait :)

Need to document it, and add to the UI, for now it can be invoked like this:
```
./slackdump -emoji -base my_emojis.zip
```

`-base my_emoji.zip` sets the output to `my_emoji.zip`.  It can also be a directory, i.e. `-base some_dir`
`-emoji` sets the emoji download mode.

You can let me know your OS, and I can build a binary for you, if you wish to try it out before it's released?

**Comment by craigrandall** [comment]
Super cool! Thanks. I can wait for the upcoming release. Cheers!

**Comment by rusq** [comment]
Hey @craigrandall, version [2.2.0](https://github.com/rusq/slackdump/releases/tag/v2.2.0) has the `-emoji` flag built in that allows to download the emojis, see [this documentation section](https://github.com/rusq/slackdump/blob/master/doc/usage-emoji.rst).

Thank you for your patience!

**Comment by craigrandall** [comment]
Outstanding! Will give this release a spin...
