### ISSUE TITLE
Program won't open on Windows

### ISSUE THREAD

**Issue by alexmayberry** [rusq/slackdump#61]
**Describe the bug**
When I try to run slackdump.exe, a window opens and then immediately disappears. 

**To Reproduce**
I open the file.

**Expected behavior**
I expect the program to open and run but there seems to be a compatibility issue that the windows compatibility wizard can't identify. 

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
Sorry, I know this is probably too vague and submitted in the wrong place, but I would love to use this tool and have no idea how to resolve this issue. Thank you.

**Comment by rusq** [comment]
Hey @alexmayberry , no worries.

Which version are you using?

**Comment by rusq** [comment]
Probably the documentation isn't clear enough - you need to open the application in the command line prompt.

https://github.com/rusq/slackdump/blob/master/doc/README.rst#id2

Between items 2 and 3 - it should read "open Command Prompt"

Then follow one of these guides:
- List users: https://github.com/rusq/slackdump/blob/master/doc/usage-list.rst
- Dump channel: https://github.com/rusq/slackdump/blob/master/doc/usage-channels.rst
- Generate a Slack Export: https://github.com/rusq/slackdump/blob/master/doc/usage-export.rst
