### ISSUE TITLE
Slack-export compatibility

### ISSUE THREAD

**Issue by rusq** [rusq/slackdump#63]
v2.0.0-rc

- [x] Seems it [causes slack-export to crash](https://github.com/hfaran/slack-export-viewer/issues/148)
- [ ] Also, reports of inability to import the export into newly created workspace.

> Also, it is expected that attachment won't be imported.  When one creates an export using the Slack workspace export, what happens is 1) Slack generates a special "export token" 2) all export json conversation files links are updated to include this token in the URL.  So the files are still hosted on slack and not physically downloaded into the ZIP archive generated by slack.  I suspect, that when one imports the conversations, Slack tries to access those links to remap the files to the new workspace.  Potentially the solution would be to start a web server that Slack can see, update all file links in conversations to this sever address to let the new Slack workspace download it, if that was happens, but this is just my guess

**Comment by omarcostahamido** [comment]
_fuhyoo!_
you're also using slack-export-viewer! I wish you had noted it on the readme somewhere.
So, the only way I was able to make this sorta work was by commenting out lines 253 and 254 on reader.py, AND by filling in the `name` and `name_normalized` fields on the `channels.json` exported file.
Hope this helps in any way...

**Comment by rusq** [comment]
Hey @omarcostahamido , haha, yeah, someone has requested slack-export compatibility a while back, so ATM I'm sorting it out.  Thank you for the suggestion, that's helpful!

**Comment by rusq** [comment]
Submitted PR in the upstream to fix the KeyNotFound exception

**Comment by rusq** [comment]
Checking `name` and `name_normalized` - the problem seems to be originating from these 3 facts.
1. Users do not have "name" and "name_normalized" populated.
2. Original Slack Workspace Export does not export users
3. Slack-export does not expect to see users in the list.

I think for this particular case I'll just populate the name and name_normalized with user names, when available.

**Comment by rusq** [comment]
This commit fixes the population of `name` and `name_normalized` https://github.com/rusq/slackdump/commit/eb604e95dc4c43e9cf7d7d755ac81ec75bb1fc3c

**Comment by fdev** [comment]
>     2. Original Slack Workspace Export does not export users

According to the [docs page](https://slack.com/help/articles/220556107-How-to-read-Slack-data-exports) I found, the official Slack Export contains:
* `channels.json` for public channel messages
* `groups.json` for private channel messages
* `dms.json` for direct messages
* `mpims.json` for group direct messages
* `users.json` for members

This tool currently only exports `channels.json` and `users.json` so the Slack Export Viewer, that _does_ have separate sections in its interface for the different message types, groups everything together as public channels (with some very unreadable names).

**Comment by rusq** [comment]
@fdev thanks for the info, great finding.  That's probably only available on an enterprise plan? I guess the only problem here would be to figure out the directory structure for those `dms`, `groups` and `mpims`.  I won't hold my breath, but if anyone reading this thread could share the output of the `tree` for such an archive, it would really help.

**Comment by rusq** [comment]
- [ ] mention slack export in docs

**Comment by omarcostahamido** [comment]
> * [ ]  mention slack export viewer in docs

_haiyaa!..._
put checkbox item on OP todo list!

**Comment by omarcostahamido** [comment]
@fdev great catch. Thanks!

**Comment by rusq** [comment]
Channel split implemented in 36728b5f33910

**Comment by rusq** [comment]
Changes are in master, if someone wants to have a squiz

**Comment by rusq** [comment]
Slack export compatibility is resolved.  If the issue with importing ZIP files persists, will open another issue.  Thank you for your contribution [@neznakomec](https://github.com/Neznakomec) @omarcostahamido @fdev  :)
