### ISSUE TITLE
Release for Mac OS X?

### ISSUE THREAD

**Issue by blackdrago** [rusq/slackdump#7]
I downloaded the Linux release to attempt to execute on my Mac OS X machine. I've checked the file settings, and it's executable, but when I try to run it, I keep getting "slackdump: command not found".

Have I missed a step during unpacking? (I simply unzipped the file and proceeded). Or did I download the wrong release file?

I'm new to Go, so I apologize if I'm missing something super obvious. I'm very excited about this package's functionality!

**Comment by rusq** [comment]
Hey @blackdrago ,

It seems that there's possibly two possible issues here:
1. Linux version does not run on Mac
2. You're trying to execute slackdump, but it's not in your path.

Fixes:
1. For MacOS you should download [slackdump-darwin.zip](https://github.com/rusq/slackdump/releases/download/v1.1.1/slackdump-darwin.zip)
2. When unpacked, try running it like this `./slackdump` - this will execute it from the current directory.

I should probably explicitly mention that MacOS users should download `darwin` release.

**Comment by blackdrago** [comment]
This worked perfectly for me! Thank you!
