### ISSUE TITLE
Compatibility with slack-export format

### ISSUE THREAD

**Issue by rusq** [rusq/slackdump#9]
Suggestion in the telegram channel to be able to open the export with https://github.com/hfaran/slack-export-viewer.  For this, will need to adjust the export structure to match that of slack export.  Example: https://github.com/hfaran/slack-export-viewer/blob/master/tests/testarchive.zip

**Comment by foucist** [comment]
I checked a couple of other viewers, they seem to expect a directory that follows a certain format, which includes users.json and so on.
