### ISSUE TITLE
Export to Markdown

### ISSUE THREAD

**Issue by jmgarnier** [rusq/slackdump#95]
**Describe the solution you'd like**
```
slackdump -r markdown
```

with images

**Describe alternatives you've considered**
I can find a tool which convert text to markdown.

**Additional context**
I believe there will be go libraries to convert Slack format (HTML in json?) to Markdown

**Comment by rusq** [comment]
I could certainly look into this in future.

Had a look at what's there in the internets, found this app: https://github.com/ohtake/slack2md that converts slack export to markdown files.

I ran it for the export of my slack workspace and it generated a bunch of MD files:
```
-rw-r--r--  1 rustam  wheel    100 Jul 23 11:56 channel--everyone.md
-rw-r--r--  1 rustam  wheel    104 Jul 23 11:56 channel--everything.md
-rw-r--r--  1 rustam  wheel    246 Jul 23 11:56 channel--random.md
-rw-r--r--  1 rustam  wheel    100 Jul 23 11:56 channel--wakatime.md
-rw-r--r--  1 rustam  wheel    481 Jul 23 11:56 history--everyone--1.md
-rw-r--r--  1 rustam  wheel    600 Jul 23 11:56 history--everything--1.md
-rw-r--r--  1 rustam  wheel  25673 Jul 23 11:56 history--random--1.md
-rw-r--r--  1 rustam  wheel  28025 Jul 23 11:56 history--random--2.md
-rw-r--r--  1 rustam  wheel   5345 Jul 23 11:56 history--random--3.md
-rw-r--r--  1 rustam  wheel   5407 Jul 23 11:56 history--wakatime--1.md
-rw-r--r--  1 rustam  wheel   1408 Jul 23 11:56 index.md
```

Have you tried it?

**Comment by jmgarnier** [comment]
Thanks for the reply :) My goal is to turn a Slack thread to a wiki page for documentation purpose.

`slack2md` includes the messages author & time, which is a lot of noise.

**Comment by rusq** [comment]
@jmgarnier nice idea! I don't think I completely understand how it should look like?  Could you elaborate more please?

When you say "thread" - are you referring to a Slack thread replies, or the whole Conversation (channel messages + thread messages)?

Should it have the same format as current "text mode" dump, only in Markdown?

**Comment by rusq** [comment]
v3.0.0 will include an experimental viewer for slackdump supported archive formats.
